/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EvidenceRegistry {
  export type AuditEntryStruct = {
    category: BigNumberish;
    severity: BigNumberish;
    description: string;
    investigator: AddressLike;
    investigationId: string;
    evidenceId: string;
    timestamp: BigNumberish;
    metadata: BytesLike;
    eventHash: BytesLike;
  };

  export type AuditEntryStructOutput = [
    category: bigint,
    severity: bigint,
    description: string,
    investigator: string,
    investigationId: string,
    evidenceId: string,
    timestamp: bigint,
    metadata: string,
    eventHash: string
  ] & {
    category: bigint;
    severity: bigint;
    description: string;
    investigator: string;
    investigationId: string;
    evidenceId: string;
    timestamp: bigint;
    metadata: string;
    eventHash: string;
  };

  export type EvidenceDataStruct = {
    evidenceId: string;
    evidenceHash: BytesLike;
    timestamp: BigNumberish;
    investigator: AddressLike;
    investigationId: string;
    verificationStatus: BigNumberish;
    metadata: BytesLike;
  };

  export type EvidenceDataStructOutput = [
    evidenceId: string,
    evidenceHash: string,
    timestamp: bigint,
    investigator: string,
    investigationId: string,
    verificationStatus: bigint,
    metadata: string
  ] & {
    evidenceId: string;
    evidenceHash: string;
    timestamp: bigint;
    investigator: string;
    investigationId: string;
    verificationStatus: bigint;
    metadata: string;
  };

  export type VerificationRecordStruct = {
    evidenceId: string;
    verifier: AddressLike;
    timestamp: BigNumberish;
    result: boolean;
    expectedHash: BytesLike;
    actualHash: BytesLike;
    status: BigNumberish;
  };

  export type VerificationRecordStructOutput = [
    evidenceId: string,
    verifier: string,
    timestamp: bigint,
    result: boolean,
    expectedHash: string,
    actualHash: string,
    status: bigint
  ] & {
    evidenceId: string;
    verifier: string;
    timestamp: bigint;
    result: boolean;
    expectedHash: string;
    actualHash: string;
    status: bigint;
  };
}

export interface EvidenceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "STATE_LOCKED"
      | "STATE_PENDING"
      | "STATE_REGISTERED"
      | "STATE_TRANSFERRED"
      | "auditEntryCount"
      | "batchRegisterEvidence"
      | "checkEvidenceExists"
      | "createAuditEntry"
      | "evidenceCount"
      | "getAllEvidenceIds"
      | "getAuditEntry"
      | "getContractInfo"
      | "getEvidence"
      | "getEvidenceAudit"
      | "getEvidenceHash"
      | "getEvidenceStatus"
      | "getInvestigationAudit"
      | "getInvestigationEvidenceCount"
      | "getRecentAuditEntries"
      | "getVerificationHistory"
      | "markEvidenceInvalid"
      | "owner"
      | "recordEvidenceRegistration"
      | "recordSystemEvent"
      | "recordTamperDetection"
      | "recordVerificationResult"
      | "registerEvidence"
      | "updateEvidenceStatus"
      | "verifyEvidence"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuditEntryCreated"
      | "CriticalAuditEvent"
      | "EvidenceAuditEvent"
      | "EvidenceRegistered"
      | "EvidenceStatusUpdated"
      | "EvidenceVerified"
      | "VerificationAuditEvent"
      | "VerificationFailed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "STATE_LOCKED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STATE_PENDING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STATE_REGISTERED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STATE_TRANSFERRED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auditEntryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchRegisterEvidence",
    values: [string[], BytesLike[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkEvidenceExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuditEntry",
    values: [BigNumberish, BigNumberish, string, string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "evidenceCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEvidenceIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractInfo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getEvidence", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getEvidenceAudit",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidenceHash",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidenceStatus",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestigationAudit",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestigationEvidenceCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentAuditEntries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationHistory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "markEvidenceInvalid",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordEvidenceRegistration",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordSystemEvent",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordTamperDetection",
    values: [string, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordVerificationResult",
    values: [string, string, boolean, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEvidence",
    values: [string, BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEvidenceStatus",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEvidence",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "STATE_LOCKED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STATE_PENDING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STATE_REGISTERED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STATE_TRANSFERRED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auditEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchRegisterEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkEvidenceExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuditEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evidenceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEvidenceIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidenceAudit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidenceHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidenceStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvestigationAudit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvestigationEvidenceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentAuditEntries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markEvidenceInvalid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordEvidenceRegistration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSystemEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordTamperDetection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordVerificationResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEvidenceStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace AuditEntryCreatedEvent {
  export type InputTuple = [
    entryIndex: BigNumberish,
    category: BigNumberish,
    severity: BigNumberish,
    investigator: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    entryIndex: bigint,
    category: bigint,
    severity: bigint,
    investigator: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    entryIndex: bigint;
    category: bigint;
    severity: bigint;
    investigator: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CriticalAuditEventEvent {
  export type InputTuple = [
    entryIndex: BigNumberish,
    description: string,
    investigator: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    entryIndex: bigint,
    description: string,
    investigator: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    entryIndex: bigint;
    description: string;
    investigator: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceAuditEventEvent {
  export type InputTuple = [
    entryIndex: BigNumberish,
    evidenceId: string,
    action: string,
    investigator: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    entryIndex: bigint,
    evidenceId: string,
    action: string,
    investigator: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    entryIndex: bigint;
    evidenceId: string;
    action: string;
    investigator: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceRegisteredEvent {
  export type InputTuple = [
    evidenceId: string,
    evidenceHash: BytesLike,
    investigator: AddressLike,
    timestamp: BigNumberish,
    investigationId: string
  ];
  export type OutputTuple = [
    evidenceId: string,
    evidenceHash: string,
    investigator: string,
    timestamp: bigint,
    investigationId: string
  ];
  export interface OutputObject {
    evidenceId: string;
    evidenceHash: string;
    investigator: string;
    timestamp: bigint;
    investigationId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceStatusUpdatedEvent {
  export type InputTuple = [
    evidenceId: string,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    updater: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    evidenceId: string,
    oldStatus: bigint,
    newStatus: bigint,
    updater: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    evidenceId: string;
    oldStatus: bigint;
    newStatus: bigint;
    updater: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceVerifiedEvent {
  export type InputTuple = [
    evidenceId: string,
    verifier: AddressLike,
    result: boolean,
    status: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    evidenceId: string,
    verifier: string,
    result: boolean,
    status: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    evidenceId: string;
    verifier: string;
    result: boolean;
    status: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationAuditEventEvent {
  export type InputTuple = [
    entryIndex: BigNumberish,
    evidenceId: string,
    success: boolean,
    investigator: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    entryIndex: bigint,
    evidenceId: string,
    success: boolean,
    investigator: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    entryIndex: bigint;
    evidenceId: string;
    success: boolean;
    investigator: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationFailedEvent {
  export type InputTuple = [
    evidenceId: string,
    verifier: AddressLike,
    expectedHash: BytesLike,
    actualHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    evidenceId: string,
    verifier: string,
    expectedHash: string,
    actualHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    evidenceId: string;
    verifier: string;
    expectedHash: string;
    actualHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EvidenceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): EvidenceRegistry;
  waitForDeployment(): Promise<this>;

  interface: EvidenceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  STATE_LOCKED: TypedContractMethod<[], [bigint], "view">;

  STATE_PENDING: TypedContractMethod<[], [bigint], "view">;

  STATE_REGISTERED: TypedContractMethod<[], [bigint], "view">;

  STATE_TRANSFERRED: TypedContractMethod<[], [bigint], "view">;

  auditEntryCount: TypedContractMethod<[], [bigint], "view">;

  batchRegisterEvidence: TypedContractMethod<
    [
      _evidenceIds: string[],
      _evidenceHashes: BytesLike[],
      _investigationId: string
    ],
    [boolean],
    "nonpayable"
  >;

  checkEvidenceExists: TypedContractMethod<
    [_evidenceId: string],
    [boolean],
    "view"
  >;

  createAuditEntry: TypedContractMethod<
    [
      _category: BigNumberish,
      _severity: BigNumberish,
      _description: string,
      _investigationId: string,
      _evidenceId: string,
      _metadata: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  evidenceCount: TypedContractMethod<[], [bigint], "view">;

  getAllEvidenceIds: TypedContractMethod<[], [string[]], "view">;

  getAuditEntry: TypedContractMethod<
    [_index: BigNumberish],
    [EvidenceRegistry.AuditEntryStructOutput],
    "view"
  >;

  getContractInfo: TypedContractMethod<[], [[string, string, bigint]], "view">;

  getEvidence: TypedContractMethod<
    [_evidenceId: string],
    [EvidenceRegistry.EvidenceDataStructOutput],
    "view"
  >;

  getEvidenceAudit: TypedContractMethod<
    [_evidenceId: string],
    [EvidenceRegistry.AuditEntryStructOutput[]],
    "view"
  >;

  getEvidenceHash: TypedContractMethod<[_evidenceId: string], [string], "view">;

  getEvidenceStatus: TypedContractMethod<
    [_evidenceId: string],
    [bigint],
    "view"
  >;

  getInvestigationAudit: TypedContractMethod<
    [_investigationId: string],
    [EvidenceRegistry.AuditEntryStructOutput[]],
    "view"
  >;

  getInvestigationEvidenceCount: TypedContractMethod<
    [_investigationId: string],
    [bigint],
    "view"
  >;

  getRecentAuditEntries: TypedContractMethod<
    [_count: BigNumberish],
    [EvidenceRegistry.AuditEntryStructOutput[]],
    "view"
  >;

  getVerificationHistory: TypedContractMethod<
    [_evidenceId: string],
    [EvidenceRegistry.VerificationRecordStructOutput[]],
    "view"
  >;

  markEvidenceInvalid: TypedContractMethod<
    [_evidenceId: string, _reason: string],
    [boolean],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordEvidenceRegistration: TypedContractMethod<
    [_evidenceId: string, _investigationId: string, _hash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  recordSystemEvent: TypedContractMethod<
    [_description: string, _metadata: BytesLike],
    [bigint],
    "nonpayable"
  >;

  recordTamperDetection: TypedContractMethod<
    [
      _evidenceId: string,
      _investigationId: string,
      _expectedHash: BytesLike,
      _actualHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  recordVerificationResult: TypedContractMethod<
    [
      _evidenceId: string,
      _investigationId: string,
      _success: boolean,
      _expectedHash: BytesLike,
      _actualHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  registerEvidence: TypedContractMethod<
    [
      _evidenceId: string,
      _evidenceHash: BytesLike,
      _investigationId: string,
      _metadata: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  updateEvidenceStatus: TypedContractMethod<
    [_evidenceId: string, _newStatus: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  verifyEvidence: TypedContractMethod<
    [_evidenceId: string, _hashToVerify: BytesLike],
    [[boolean, bigint]],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "STATE_LOCKED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STATE_PENDING"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STATE_REGISTERED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STATE_TRANSFERRED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "auditEntryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchRegisterEvidence"
  ): TypedContractMethod<
    [
      _evidenceIds: string[],
      _evidenceHashes: BytesLike[],
      _investigationId: string
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkEvidenceExists"
  ): TypedContractMethod<[_evidenceId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "createAuditEntry"
  ): TypedContractMethod<
    [
      _category: BigNumberish,
      _severity: BigNumberish,
      _description: string,
      _investigationId: string,
      _evidenceId: string,
      _metadata: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "evidenceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllEvidenceIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAuditEntry"
  ): TypedContractMethod<
    [_index: BigNumberish],
    [EvidenceRegistry.AuditEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractInfo"
  ): TypedContractMethod<[], [[string, string, bigint]], "view">;
  getFunction(
    nameOrSignature: "getEvidence"
  ): TypedContractMethod<
    [_evidenceId: string],
    [EvidenceRegistry.EvidenceDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvidenceAudit"
  ): TypedContractMethod<
    [_evidenceId: string],
    [EvidenceRegistry.AuditEntryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvidenceHash"
  ): TypedContractMethod<[_evidenceId: string], [string], "view">;
  getFunction(
    nameOrSignature: "getEvidenceStatus"
  ): TypedContractMethod<[_evidenceId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getInvestigationAudit"
  ): TypedContractMethod<
    [_investigationId: string],
    [EvidenceRegistry.AuditEntryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInvestigationEvidenceCount"
  ): TypedContractMethod<[_investigationId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRecentAuditEntries"
  ): TypedContractMethod<
    [_count: BigNumberish],
    [EvidenceRegistry.AuditEntryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVerificationHistory"
  ): TypedContractMethod<
    [_evidenceId: string],
    [EvidenceRegistry.VerificationRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "markEvidenceInvalid"
  ): TypedContractMethod<
    [_evidenceId: string, _reason: string],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordEvidenceRegistration"
  ): TypedContractMethod<
    [_evidenceId: string, _investigationId: string, _hash: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordSystemEvent"
  ): TypedContractMethod<
    [_description: string, _metadata: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordTamperDetection"
  ): TypedContractMethod<
    [
      _evidenceId: string,
      _investigationId: string,
      _expectedHash: BytesLike,
      _actualHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordVerificationResult"
  ): TypedContractMethod<
    [
      _evidenceId: string,
      _investigationId: string,
      _success: boolean,
      _expectedHash: BytesLike,
      _actualHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerEvidence"
  ): TypedContractMethod<
    [
      _evidenceId: string,
      _evidenceHash: BytesLike,
      _investigationId: string,
      _metadata: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateEvidenceStatus"
  ): TypedContractMethod<
    [_evidenceId: string, _newStatus: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyEvidence"
  ): TypedContractMethod<
    [_evidenceId: string, _hashToVerify: BytesLike],
    [[boolean, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AuditEntryCreated"
  ): TypedContractEvent<
    AuditEntryCreatedEvent.InputTuple,
    AuditEntryCreatedEvent.OutputTuple,
    AuditEntryCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CriticalAuditEvent"
  ): TypedContractEvent<
    CriticalAuditEventEvent.InputTuple,
    CriticalAuditEventEvent.OutputTuple,
    CriticalAuditEventEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceAuditEvent"
  ): TypedContractEvent<
    EvidenceAuditEventEvent.InputTuple,
    EvidenceAuditEventEvent.OutputTuple,
    EvidenceAuditEventEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceRegistered"
  ): TypedContractEvent<
    EvidenceRegisteredEvent.InputTuple,
    EvidenceRegisteredEvent.OutputTuple,
    EvidenceRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceStatusUpdated"
  ): TypedContractEvent<
    EvidenceStatusUpdatedEvent.InputTuple,
    EvidenceStatusUpdatedEvent.OutputTuple,
    EvidenceStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceVerified"
  ): TypedContractEvent<
    EvidenceVerifiedEvent.InputTuple,
    EvidenceVerifiedEvent.OutputTuple,
    EvidenceVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationAuditEvent"
  ): TypedContractEvent<
    VerificationAuditEventEvent.InputTuple,
    VerificationAuditEventEvent.OutputTuple,
    VerificationAuditEventEvent.OutputObject
  >;
  getEvent(
    key: "VerificationFailed"
  ): TypedContractEvent<
    VerificationFailedEvent.InputTuple,
    VerificationFailedEvent.OutputTuple,
    VerificationFailedEvent.OutputObject
  >;

  filters: {
    "AuditEntryCreated(uint256,uint8,uint8,address,uint256)": TypedContractEvent<
      AuditEntryCreatedEvent.InputTuple,
      AuditEntryCreatedEvent.OutputTuple,
      AuditEntryCreatedEvent.OutputObject
    >;
    AuditEntryCreated: TypedContractEvent<
      AuditEntryCreatedEvent.InputTuple,
      AuditEntryCreatedEvent.OutputTuple,
      AuditEntryCreatedEvent.OutputObject
    >;

    "CriticalAuditEvent(uint256,string,address,uint256)": TypedContractEvent<
      CriticalAuditEventEvent.InputTuple,
      CriticalAuditEventEvent.OutputTuple,
      CriticalAuditEventEvent.OutputObject
    >;
    CriticalAuditEvent: TypedContractEvent<
      CriticalAuditEventEvent.InputTuple,
      CriticalAuditEventEvent.OutputTuple,
      CriticalAuditEventEvent.OutputObject
    >;

    "EvidenceAuditEvent(uint256,string,string,address,uint256)": TypedContractEvent<
      EvidenceAuditEventEvent.InputTuple,
      EvidenceAuditEventEvent.OutputTuple,
      EvidenceAuditEventEvent.OutputObject
    >;
    EvidenceAuditEvent: TypedContractEvent<
      EvidenceAuditEventEvent.InputTuple,
      EvidenceAuditEventEvent.OutputTuple,
      EvidenceAuditEventEvent.OutputObject
    >;

    "EvidenceRegistered(string,bytes32,address,uint256,string)": TypedContractEvent<
      EvidenceRegisteredEvent.InputTuple,
      EvidenceRegisteredEvent.OutputTuple,
      EvidenceRegisteredEvent.OutputObject
    >;
    EvidenceRegistered: TypedContractEvent<
      EvidenceRegisteredEvent.InputTuple,
      EvidenceRegisteredEvent.OutputTuple,
      EvidenceRegisteredEvent.OutputObject
    >;

    "EvidenceStatusUpdated(string,uint8,uint8,address,uint256)": TypedContractEvent<
      EvidenceStatusUpdatedEvent.InputTuple,
      EvidenceStatusUpdatedEvent.OutputTuple,
      EvidenceStatusUpdatedEvent.OutputObject
    >;
    EvidenceStatusUpdated: TypedContractEvent<
      EvidenceStatusUpdatedEvent.InputTuple,
      EvidenceStatusUpdatedEvent.OutputTuple,
      EvidenceStatusUpdatedEvent.OutputObject
    >;

    "EvidenceVerified(string,address,bool,uint8,uint256)": TypedContractEvent<
      EvidenceVerifiedEvent.InputTuple,
      EvidenceVerifiedEvent.OutputTuple,
      EvidenceVerifiedEvent.OutputObject
    >;
    EvidenceVerified: TypedContractEvent<
      EvidenceVerifiedEvent.InputTuple,
      EvidenceVerifiedEvent.OutputTuple,
      EvidenceVerifiedEvent.OutputObject
    >;

    "VerificationAuditEvent(uint256,string,bool,address,uint256)": TypedContractEvent<
      VerificationAuditEventEvent.InputTuple,
      VerificationAuditEventEvent.OutputTuple,
      VerificationAuditEventEvent.OutputObject
    >;
    VerificationAuditEvent: TypedContractEvent<
      VerificationAuditEventEvent.InputTuple,
      VerificationAuditEventEvent.OutputTuple,
      VerificationAuditEventEvent.OutputObject
    >;

    "VerificationFailed(string,address,bytes32,bytes32,uint256)": TypedContractEvent<
      VerificationFailedEvent.InputTuple,
      VerificationFailedEvent.OutputTuple,
      VerificationFailedEvent.OutputObject
    >;
    VerificationFailed: TypedContractEvent<
      VerificationFailedEvent.InputTuple,
      VerificationFailedEvent.OutputTuple,
      VerificationFailedEvent.OutputObject
    >;
  };
}
